Add the milestone delivery for phase 1 of Reclaim Protocol
pioneersprize/Milestone-Delivery pull request #5
Opened 2024-08-06 14:31 UTC by rohit-goswami

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/pioneersprize/Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the account provided in the application.

Link to the application pull request: https://github.com/pioneersprize/Polkadot-Pioneers-Prize/pull/13

2024-08-26 03:03 UTC, xlc commented
Deliverables

- [x] Integrating Reclaim Protocol with Polkadot - Missing Demo?
- [ ] Optimising zkProofs ??
- [x] Integration and Testing - Not a lot of tests but there are some
- [ ] Detailed Documentation and Guides - There is a doc but the proposal stated there will be blogposts and community calls?

2024-09-02 10:45 UTC, rohit-goswami commented
Hey @xlc,
First of all, apologies for the delayed response.

We'd like to first get confirmation for the integration part from the Polkadot team, and we've already worked on the blog post, which we will publish once we receive confirmation for the integration. We will also organize a community call.

Regarding the zkProofs Optimization part, the Reclaim Polkadot SDK efficiently verifies ZKPs in the no-std environment in use (https://gitlab.reclaimprotocol.org/integrations/onchain/substrate-sdk/-/blob/main/pallets/pallet-reclaim/Cargo.toml?ref_type=heads). Verification occurs using primitive types at optimized speed—try substrate benchmarking to attest. The proofs retain cross-chain properties as cryptographic commitments are Ethereum compatible (Keccak and ECDSA).

Looking forward to the confirmation, and let me know if you have any further questions.

Thank you.

2024-09-09 06:58 UTC, rohit-goswami commented
Hey @xlc,

Please check this [blog ](https://questbook.notion.site/Polkadot-Blog-09e8bd01c81744bdbde912ab2a4643c8)post, I'd love to know your feedback before we publish it.

Also, we made an official [twitter ](https://x.com/reclaimprotocol/status/1831399357641585122?s=46) annoncement of integrating with Polkadot.

2024-09-23 22:57 UTC, Subhash-Karri commented
Hi @xlc , quickly following up on the milestone payouts since we have completed all the milestones. What is the process for the same? Thank you

2024-09-23 23:36 UTC, xlc commented
I am pinging other curators for their review

2024-09-24 05:03 UTC, Noc2 requested changes
Could you update the deliverable table to include all the rows from the milestone here: https://github.com/pioneersprize/Polkadot-Pioneers-Prize/blob/main/applications/zklogin-Reclaim-protocol.md#phase---1?

2024-09-24 12:16 UTC, rohit-goswami commented
Hey @Noc2, I've updated the milestones submission table with all the deliverables.

2024-10-01 12:25 UTC, Noc2 requested changes
Sorry for the delay here. Could you also add the default deliverables 0a. to 0e. to the table?

2024-10-01 15:15 UTC, rohit-goswami commented
Hey @Noc2, I've added 0a to 0e as well.

2024-10-11 07:30 UTC, Noc2 requested changes
Thanks. Could you point me to the inline documentation of the code? I only see a few comments in your pallet and the readme is completely empty

2024-10-24 16:28 UTC, rohit-goswami commented
Hey @Noc2,

We've incorporated the requested changes. Let me know if everything looks good, and we look forward to moving to the next steps.

2024-12-02 07:11 UTC, Noc2 approved these changes
Sorry for the delay here. Looks good to me. I'm happy to merge it.

2024-12-02 07:11 UTC, Noc2 commented
Let me double-check with the rest.

2024-12-02 09:16 UTC, rohit-goswami commented
Thank you, @Noc2. Looking forward to getting it merged. Let me know the next steps.

2025-01-06 10:51 UTC, xlc approved these changes

2025-01-07 19:39 UTC, riusricardo approved these changes

2025-01-07 19:39 UTC, merged

2025-02-04 14:32 UTC, rohit-goswami commented
Hey @riusricardo @xlc, 

Thanks for merging our milestone PR. Please let us know the next steps to get the payment.

2025-02-11 12:58 UTC, Noc2 commented
@rohit-goswami I will try to initiate the transaction today

2025-02-12 05:42 UTC, rohit-goswami commented
Hey @Noc2, Let me know when you initiate the transaction, thanks.

2025-02-13 10:48 UTC, Noc2 commented
The transaction to create the child bounty has been initiated: https://polkadot.subscan.io/multisig_extrinsic/24686238-4?call_hash=0xefdb0ba7d6571d6f3866a9d1dd294d195e75b9475d703600fd515660491bc648 Once this is confirmed, we need to initiate another transaction for the payout.

2025-02-14 07:50 UTC, rohit-goswami commented
Hey @Noc2, let me confirm if we have access to the current wallet. The application was submitted by Ruchill, who is no longer working with us. I will update here soon.

2025-02-14 16:02 UTC, Noc2 commented
Sounds good. The child bounty was successfully created. The next step would be the payout.

2025-02-17 06:09 UTC, rohit-goswami commented
Hey @Noc2, please use this wallet address for the payout. 

 
`13Y9P5wo4sPSx1qmeXpJCBnHjSkC2W3Sjho1ASUtrNtvPrPL`

2025-02-17 06:28 UTC, Noc2 commented
@rohit-goswami, you need to update the payment address here: https://github.com/pioneersprize/Polkadot-Pioneers-Prize/blob/main/applications/zklogin-Reclaim-protocol.md via a PR.

2025-02-17 06:36 UTC, rohit-goswami commented
@Noc2, I've raised a PR to change the payment address.

https://github.com/pioneersprize/Polkadot-Pioneers-Prize/pull/20

2025-03-04 13:03 UTC, rohit-goswami commented
Hey @Noc2, Let me know when you initiate a tx to the new wallet.

2025-03-04 13:48 UTC, Noc2 commented
I just initiated the transaction

2025-03-04 13:52 UTC, rohit-goswami commented
awesome!, can I get the link to that transaction.

2025-03-07 07:12 UTC, rohit-goswami commented
hey @Noc2,  any update on the payment?

2025-03-10 14:22 UTC, rohit-goswami commented
Hey @Noc2, following up on this. Can you initiate the payment transaction if everything looks good?

2025-03-10 14:32 UTC, Noc2 commented
https://polkadot.subscan.io/extrinsic/0x8f69d94f588cbc8725d14939e7333f7e1c698a04e2ff6e4f18464236307327d9 The transaction was initiated 6 days ago and needs to be approved by the rest of the multi-sig.

2025-03-19 06:37 UTC, rohit-goswami commented
Hey @Noc2, the multi-sig transaction is complete. can we move forward with the payment?

2025-03-19 07:09 UTC, Noc2 commented
The transaction was successfully executed https://polkadot.subscan.io/extrinsic/25098937-2 with your account as a payment address: 13Y9P5wo4sPSx1qmeXpJCBnHjSkC2W3Sjho1ASUtrNtvPrPL Not sure what went wrong here, but the child bounty was officially paid out to your address. You might want to transfer one dot to your account for testing.

2025-03-19 07:14 UTC, Noc2 commented
See https://polkadot.dotreasury.com/#/child-bounties/3353

2025-03-19 09:21 UTC, rohit-goswami commented
Gotcha! This is helpful. Thanks for sharing and for the payment, appreciate your help! @Noc2

2025-05-07 06:05 UTC, rohit-goswami commented
Hi @Noc2, hope you're doing well.

I wanted to confirm - our agreed Phase 1 grant amount was $45K, but we’ve received approxi. $35K (7814 DOT). we haven’t received the remaining $10K. Could you help clarify if something is pending on our end or if there’s been a change?

2025-05-07 10:16 UTC, Noc2 commented
The payout was done correct according to the following calculation: 45,000/5.759 (EMA30 at the time the transaction was initiated) = 7814 DOT.